// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: imrpc.proto

package imrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Imrpc_Ping_FullMethodName = "/imrpc.Imrpc/Ping"
)

// ImrpcClient is the client API for Imrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImrpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type imrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewImrpcClient(cc grpc.ClientConnInterface) ImrpcClient {
	return &imrpcClient{cc}
}

func (c *imrpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Imrpc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImrpcServer is the server API for Imrpc service.
// All implementations must embed UnimplementedImrpcServer
// for forward compatibility.
type ImrpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedImrpcServer()
}

// UnimplementedImrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImrpcServer struct{}

func (UnimplementedImrpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedImrpcServer) mustEmbedUnimplementedImrpcServer() {}
func (UnimplementedImrpcServer) testEmbeddedByValue()               {}

// UnsafeImrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImrpcServer will
// result in compilation errors.
type UnsafeImrpcServer interface {
	mustEmbedUnimplementedImrpcServer()
}

func RegisterImrpcServer(s grpc.ServiceRegistrar, srv ImrpcServer) {
	// If the following call pancis, it indicates UnimplementedImrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Imrpc_ServiceDesc, srv)
}

func _Imrpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImrpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imrpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImrpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Imrpc_ServiceDesc is the grpc.ServiceDesc for Imrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Imrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imrpc.Imrpc",
	HandlerType: (*ImrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Imrpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imrpc.proto",
}
